/**
 * Creates an iterable where all elements are generated by the given function based on the index.
 * @param generateElement a function that accepts an index and produces the element to be generated at that index.
 * @param length the number of elements to generate. If not given, elements will be generated infinitely.
 */
export default function* generate<T>(
  generateElement: (index: number) => T,
  length?: number
): Generator<T> {
  for (let index = 0; length == null ? true : index < length; index++) {
    yield generateElement(index);
  }
}
